### ISSUE TITLE
Link to the website is not working

### ISSUE THREAD

**Issue by jpzs444** [midopooler/PersonalWebsite#15]
![image](https://user-images.githubusercontent.com/75724780/106590123-bf55e580-6587-11eb-826b-9c16fcec436c.png)

Do update the link as soon as you are ready so that other people can take a look at your website. 😄

**Comment by midopooler** [comment]
Hey what's the URL which you are browsing?

**Comment by jpzs444** [comment]
I forgot to specify, sorry about that! It's the URL in the README file. Also, is that icon at the bottom supposed to be an image?  
![image](https://user-images.githubusercontent.com/75724780/106594772-89b3fb00-658d-11eb-8123-5eb237ff44c0.png)

**Comment by midopooler** [comment]
fixed

**Comment by jpzs444** [comment]
Your website looks good! Thank you for your time and good luck with your projects. 😄
